import { useEffect, useState } from "react"
import Head from 'next/head';
import { Button } from '../components/Box';

export default function Home() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    (async () => {
      const a = await fetch("/api/hello");
      const { name } = await a.json();
      setMessage(name);
    })()
  }, [])


  return (
    <div>
      <Head>
        <title>{message}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button $as="a" href="#">Hello {message}</Button>
    </div>
  )
}
